api_version = "2025-01"

[[extensions]]
type = "ui_extension"
name = "Management page"
handle = "buyer-subscriptions"

  [[extensions.targeting]]
  module = "./src/index.tsx"
  target = "customer-account.page.render"

  [extensions.capabilities]
  api_access = true
  network_access = true
